###
POST /weka/prediction HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "accountNumber": 2,
    "ipLogin": 3
}
###

POST /weka/base/prediction HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "accountNum": 20,
    "ipLogin": 10,
    "accountLimited": 10,
    "seats":1,
    "ruleIndependentNum":10,
    "ays":10000,
    "dbAys":1000,
    "dbSearch":100,
    "dbSuper":1,
    "dbTrial":1,
    "pro":1,
    "landscape":1,
    "npl":1000,
    "smeBasic":1,
    "workspace":100000,
    "chemicalMoc":1,
    "ipreportPro":1,
    "insights":1,
    "renew":1
}
###
POST /weka/mixed/prediction HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "accountNum": 1,
    "ipLogin": 1,
    "seats":10,
    "loginNum":80,
    "ruleIndependentNum":0,
    "ays":0,
    "dbAys":0,
    "dbSearch":93,
    "dbSuper":0,
    "dbTrial":0,
    "pro":0,
    "landscape":36,
    "npl":0,
    "smeBasic":0,
    "workspace":0,
    "chemicalMoc":0,
    "ipreportPro":0,
    "insights":0,

    "searchNum":0,
    "exportNum":0,

    "analysisNum":1,
    "landscapeNum":0,
    "viewNum":0,
    "chemicalNum":0,
    "alertCreatedNum":0,
    "workSpaceCreatedNum":1,
    "renew":0
}
###